"""Add unique constraint for food and unit in unit_conversion

Revision ID: d964e73bce90
Revises: 05db11b983e1
Create Date: 2024-07-14 01:16:18.241719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd964e73bce90'
down_revision = '05db11b983e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_conversion', schema=None) as batch_op:
        batch_op.create_unique_constraint('_food_unit_uc', ['food', 'unit'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_conversion', schema=None) as batch_op:
        batch_op.drop_constraint('_food_unit_uc', type_='unique')

    # ### end Alembic commands ###
